import type { Field } from "./questionnaire";

// TMP Medical Malpractice intake — mapped section-by-section from the TMP script.
// scope:"lead" fields store in claims.answers. surface:"contact" fields show on
// the Contact Info tab (shared). No retainer / no signing at intake.

export const MEDMAL_INTAKE: Field[] = [
  // SECTION 1 — ATTORNEY STATUS (DQ)
  { id: "s_attorney", scope: "lead", kind: "section", label: "Attorney Status" },
  { id: "mm_script_dq", scope: "lead", kind: "script", label: "Ask all three separately, verbatim",
    script: "Ask each of the next three questions separately and verbatim. Two of them are hard disqualifiers." },
  { id: "mm_rep_now", scope: "lead", kind: "bool", vital: true, gateType: "dq",
    label: "Are you currently represented by another attorney for this matter?",
    agentNote: "If YES — STOP. Disqualify. End the call politely." },
  { id: "mm_spoke_attorney", scope: "lead", kind: "bool",
    label: "Have you spoken to another attorney about this matter?",
    agentNote: "Informational only. YES does NOT disqualify. Continue regardless." },
  { id: "mm_signed_firm", scope: "lead", kind: "bool", vital: true, gateType: "dq",
    label: "Have you signed any documents with another law firm about this matter?",
    agentNote: "If YES — STOP. Disqualify. End the call politely." },

  // SECTION 2 — OPENING
  { id: "s_opening", scope: "lead", kind: "section", label: "Opening" },
  { id: "mm_open_script", scope: "lead", kind: "script", label: "Opening (read verbatim)",
    script: "Inbound: Thank you for calling the firm. How can I help you today? Outbound: Hi, this is [Agent] with the firm. I'm reaching out about the medical malpractice matter you contacted us about. Do you have a few minutes? I want to get all the details down so I can bring this to our attorney. Let them start. Don't interrupt. When they pause, move into the script." },
  { id: "mm_client_status", scope: "lead", kind: "select", label: "New or existing client?",
    options: ["New", "Existing (route to dept, stop here)"] },

  // SECTION 4 — WHO IS THIS FOR
  { id: "s_who", scope: "lead", kind: "section", label: "Who Is This For" },
  { id: "mm_self_other", scope: "lead", kind: "select", vital: true,
    label: "Is this about something that happened to you, or to someone else?",
    options: ["Self", "Someone else"] },
  { id: "mm_relationship_patient", scope: "lead", kind: "select",
    label: "If someone else: relationship to the patient",
    options: ["Spouse", "Child", "Parent", "Sibling", "Guardian", "Caretaker", "Other"] },
  { id: "mm_patient_minor", scope: "lead", kind: "bool", label: "Is the patient under 18 years old?" },
  { id: "mm_patient_living", scope: "lead", kind: "select", vital: true,
    label: "Is the patient still living, or have they passed away?",
    options: ["Living", "Deceased"],
    agentNote: "If deceased: say 'I'm very sorry for your loss.'" },
  { id: "mm_deceased_children", scope: "lead", kind: "bool",
    label: "If deceased: any children under 25 at the time they passed?",
    agentNote: "If yes — add notes (FL wrongful death / surviving children)." },

  // SECTION 5 — THE STORY
  { id: "s_story", scope: "lead", kind: "section", label: "The Story" },
  { id: "mm_story_script", scope: "lead", kind: "script", label: "Walk through it (read verbatim)",
    script: "Okay. I want to walk through exactly what happened, start to finish. Take your time, I'm going to ask you some specific questions along the way so I don't miss anything. There are no wrong answers, I just need the facts as you remember them." },
  { id: "mm_original_problem", scope: "lead", kind: "longtext",
    label: "What was the original medical problem you were being seen for?" },
  { id: "mm_original_treatment", scope: "lead", kind: "longtext",
    label: "How were they treating that? What did they do/prescribe, what was the plan?" },
  { id: "mm_timeline_start", scope: "lead", kind: "longtext",
    label: "Walk me through what happened, first appointment/procedure and approximate date",
    agentNote: "Follow-ups: What happened next? Then what? Who told you that and what exactly did they say? How long after? Same visit or different day? Anything else we haven't covered? Do NOT accept 'they messed up' as the whole story." },
  { id: "mm_what_wrong", scope: "lead", kind: "longtext", vital: true,
    label: "In your own words, what do you believe the provider did wrong?" },
  { id: "mm_admitted_mistake", scope: "lead", kind: "bool",
    label: "Did any provider/staff ever tell you a mistake had been made?" },
  { id: "mm_admitted_detail", scope: "lead", kind: "longtext",
    label: "If yes: who said it, and what did they tell you?" },
  { id: "mm_type", scope: "lead", kind: "select", vital: true,
    label: "Type of malpractice (categorize silently, do not read the list)",
    options: ["Surgical error","Failure to diagnose","Delayed diagnosis","Medication error","Failure to treat","Failure to monitor","Infection","Birth injury","ER negligence","Anesthesia","Nursing-home neglect","Other","None of the above (flag for attorney)"] },

  // SECTION 6 — FACILITIES, PROVIDERS & DATES
  { id: "s_facilities", scope: "lead", kind: "section", label: "Facilities, Providers & Dates" },
  { id: "mm_fac_script", scope: "lead", kind: "script", label: "Capture every facility (read verbatim)",
    script: "I need to write down every place you were treated and every provider involved. Let's go one at a time." },
  { id: "mm_facility1", scope: "lead", kind: "text", label: "Facility 1 — name" },
  { id: "mm_facility1_loc", scope: "lead", kind: "text", label: "Facility 1 — city/state" },
  { id: "mm_facility2", scope: "lead", kind: "text", label: "Facility 2 — name" },
  { id: "mm_facility2_loc", scope: "lead", kind: "text", label: "Facility 2 — city/state" },
  { id: "mm_facility3", scope: "lead", kind: "text", label: "Facility 3 — name" },
  { id: "mm_facility3_loc", scope: "lead", kind: "text", label: "Facility 3 — city/state" },
  { id: "mm_facility_addresses", scope: "lead", kind: "longtext", label: "Addresses / rough locations" },
  { id: "mm_doctors", scope: "lead", kind: "longtext", label: "Names of doctors involved (treating + others)" },
  { id: "mm_other_staff", scope: "lead", kind: "longtext", label: "Nurses, techs, other staff names remembered" },
  { id: "mm_incident_date", scope: "lead", kind: "text", label: "Approximate date of incident/procedure" },
  { id: "mm_last_treated", scope: "lead", kind: "text", label: "Last time treated with that doctor/facility" },

  // SECTION 7 — DISCOVERY TIMELINE
  { id: "s_discovery", scope: "lead", kind: "section", label: "Discovery Timeline" },
  { id: "mm_disc_script", scope: "lead", kind: "script", label: "How/when they realized (read verbatim)",
    script: "Now I want to understand how and when you realized something had gone wrong. Be as specific as you can with dates, even a rough month is helpful." },
  { id: "mm_first_noticed", scope: "lead", kind: "text", label: "When did you FIRST notice something wasn't right? (approx date)" },
  { id: "mm_how_found", scope: "lead", kind: "select",
    label: "How did you find out?", options: ["Noticed it myself", "Revealed by testing"] },
  { id: "mm_symptoms_noticed", scope: "lead", kind: "longtext", label: "If noticed yourself: what were the signs/symptoms?" },
  { id: "mm_test_type", scope: "lead", kind: "select", label: "If testing: what kind of test?",
    options: ["Bloodwork","X-ray","MRI","CT scan","Biopsy","Other"] },
  { id: "mm_test_showed", scope: "lead", kind: "longtext", label: "What did the test show?" },
  { id: "mm_told_facility", scope: "lead", kind: "bool", label: "Did you tell the doctor/facility something was wrong?" },
  { id: "mm_told_detail", scope: "lead", kind: "longtext", label: "If yes: when, and what did they say back? If no: what kept you from telling them / what did you do instead?" },
  { id: "mm_other_doc_negligence", scope: "lead", kind: "bool",
    label: "Has any OTHER doctor said this may have been caused by a mistake/negligence?" },
  { id: "mm_other_doc_detail", scope: "lead", kind: "longtext", label: "If yes: who, and what exactly did they say?" },

  // SECTION 8 — INJURIES & TREATMENT
  { id: "s_injuries", scope: "lead", kind: "section", label: "Injuries & Treatment" },
  { id: "mm_inj_script", scope: "lead", kind: "script", label: "Harm and treatment (read verbatim)",
    script: "Now let's talk about the harm this caused and what had to be done to deal with it." },
  { id: "mm_injuries", scope: "lead", kind: "longtext", vital: true, label: "What injuries/conditions resulted? Walk through everything." },
  { id: "mm_symptoms_now", scope: "lead", kind: "longtext", label: "What symptoms did they cause, and what are you still dealing with?" },
  { id: "mm_injury_treatment", scope: "lead", kind: "longtext",
    label: "Treatment needed for THIS injury (not the original problem)",
    agentNote: "Follow-ups: additional surgeries? how many? new medications?" },
  { id: "mm_still_treating", scope: "lead", kind: "bool", label: "Still being treated for it today?" },
  { id: "mm_treating_where", scope: "lead", kind: "text", label: "If yes: where and by whom? / If no: when did treatment end?" },
  { id: "mm_permanent", scope: "lead", kind: "select", label: "Are the injuries permanent (as told)?",
    options: ["Yes","No","Unsure / not told yet"] },
  { id: "mm_severe_list", scope: "lead", kind: "multiselect",
    label: "Has the patient suffered any of the following? (assess silently)",
    options: ["Permanent disability","Amputation","Loss of mobility","Organ damage","Brain injury","Paralysis","Chronic pain","Disfigurement","Emotional distress","Wrongful death"] },
  { id: "mm_severity", scope: "lead", kind: "select", label: "Severity (assess silently)",
    options: ["Severe — significant permanent injury or death","Moderate — significant pain/injury/added treatment","Minor — no permanent harm"],
    agentNote: "Be hypercritical of plastic surgery / cosmetic cases." },

  // SECTION 9 — LIMITATIONS & QUALITY OF LIFE
  { id: "s_qol", scope: "lead", kind: "section", label: "Limitations & Quality of Life" },
  { id: "mm_qol_script", scope: "lead", kind: "script", label: "Impact on life (read verbatim)",
    script: "I want the attorney to understand how this has actually affected your life, so be honest with me here." },
  { id: "mm_cant_do", scope: "lead", kind: "longtext", label: "What can't you do now that you could before? (work, mobility, daily tasks, hobbies, self/family care)" },
  { id: "mm_pain", scope: "lead", kind: "bool", label: "Ongoing pain or on pain management?" },
  { id: "mm_pain_detail", scope: "lead", kind: "longtext", label: "If yes: tell me about that." },
  { id: "mm_qol_compare", scope: "lead", kind: "longtext", label: "Quality of life now vs before the injury?" },
  { id: "mm_hospitalized", scope: "lead", kind: "bool", label: "Hospitalized because of this?" },
  { id: "mm_hospital_days", scope: "lead", kind: "int", label: "If yes: how many days?" },
  { id: "mm_missed_work", scope: "lead", kind: "bool", label: "Did you miss work?" },
  { id: "mm_missed_work_len", scope: "lead", kind: "text", label: "If yes: about how long were you out?" },

  // SECTION 10 — MEDICAL HISTORY & RECORDS
  { id: "s_history", scope: "lead", kind: "section", label: "Medical History & Records" },
  { id: "mm_prior_condition", scope: "lead", kind: "bool", label: "Same/related condition BEFORE the incident?" },
  { id: "mm_prior_detail", scope: "lead", kind: "longtext", label: "If yes: tell me about that." },
  { id: "mm_other_conditions", scope: "lead", kind: "longtext", label: "Other significant medical conditions the attorney should know?" },
  { id: "mm_records_requested", scope: "lead", kind: "bool", label: "Already requested/gotten copies of medical records?" },
  { id: "mm_records_have", scope: "lead", kind: "multiselect", label: "Copies currently held (check all)",
    options: ["Medical records","Lab results","Imaging (MRI/CT/X-ray)","Operative reports","Discharge paperwork","Bills"] },

  // SECTION 11 — BIRTH INJURY (conditional)
  { id: "s_birth", scope: "lead", kind: "section", label: "Birth Injury (if applicable)" },
  { id: "mm_child_name", scope: "lead", kind: "text", label: "Child's name" },
  { id: "mm_child_dob", scope: "lead", kind: "date", label: "Child's date of birth" },
  { id: "mm_mother_name", scope: "lead", kind: "text", label: "Mother's name" },
  { id: "mm_weeks_pregnant", scope: "lead", kind: "text", label: "Weeks pregnant at delivery" },
  { id: "mm_fetal_distress", scope: "lead", kind: "bool", label: "Fetal distress during labor/delivery?" },
  { id: "mm_emergency_csection", scope: "lead", kind: "bool", label: "Emergency C-section performed?" },
  { id: "mm_nicu", scope: "lead", kind: "bool", label: "Baby needed NICU care?" },
  { id: "mm_nicu_len", scope: "lead", kind: "text", label: "If yes: how long?" },

  // SECTION 12 — CONTACT INFO (shared → Contact Info tab)
  { id: "s_mm_contact", scope: "lead", kind: "section", label: "Contact Info", surface: "contact" },
  { id: "caller_first", scope: "lead", kind: "text", label: "First name", surface: "contact", vital: true },
  { id: "caller_last", scope: "lead", kind: "text", label: "Last name", surface: "contact", vital: true },
  { id: "caller_phone", scope: "lead", kind: "phone", label: "Best phone", surface: "contact", vital: true },
  { id: "perm_call", scope: "lead", kind: "bool", label: "Permission to contact at that number?", surface: "contact" },
  { id: "caller_email", scope: "lead", kind: "email", label: "Email", surface: "contact" },
  { id: "mail_addr1", scope: "lead", kind: "text", label: "Home address", surface: "contact" },
  { id: "mail_city", scope: "lead", kind: "text", label: "City", surface: "contact" },
  { id: "mail_state", scope: "lead", kind: "text", label: "State", surface: "contact" },
  { id: "mail_zip", scope: "lead", kind: "text", label: "Zip", surface: "contact" },
  { id: "caller_phone_alt", scope: "lead", kind: "phone", label: "Alternate phone", surface: "contact" },
  { id: "ip_dob", scope: "lead", kind: "date", label: "Date of birth", surface: "contact" },
  { id: "mm_married", scope: "lead", kind: "bool", label: "Are you married?", surface: "contact" },
  { id: "mm_spouse_name", scope: "lead", kind: "text", label: "Spouse's name", surface: "contact" },

  // SECTION 13 — CLOSE
  { id: "s_close", scope: "lead", kind: "section", label: "Close" },
  { id: "mm_close_script", scope: "lead", kind: "script", label: "Close (read verbatim)",
    script: "Okay, I've got everything I need for now. Here's what happens next. I'm going to take all of this information and present it directly to our attorney for review. He's going to look at the details and decide the best way to move forward. Then someone from our office will reach back out to you to discuss the next steps. Do you have any questions for me before we wrap up? (Answer factually. Do NOT promise the case will be taken. Do NOT quote value. Do NOT say the attorney 'will' take it, only that he'll review and we'll follow up.) Perfect. Keep your phone handy, and if you come across any medical records or paperwork, hang on to them, they'll help. Thanks for your time, we'll be in touch." },
  { id: "mm_disposition", scope: "lead", kind: "select", label: "Disposition (agent use)",
    options: ["Submitted to attorney for review — follow-up needed","Disqualified — represented / signed with another firm","Incomplete — callback scheduled"] },
  { id: "mm_attorney_notes", scope: "lead", kind: "longtext", label: "Notes for attorney" },
];
