import assert from 'node:assert/strict';
import { deterministicQa, qaSources, narrativeQa, redactQaText, type QaInput } from './report';
const input: QaInput = { flow: 'inno', answers: { story: { text: 'Stopped at a red light. Rear-ended.', date: '2026-10-02' }, body: { firstAt: '2026-10-01' }, car: { people: [{ name: 'Private Passenger', wantsRep: 'Yes', dob: '1980-01-01' }] }, file: { ssn: '123456789' }, unrelatedVendor: { text: 'DO NOT SEND' } }, contact: { phone: '2025550100', email: 'test@example.invalid', address: 'Synthetic address' }, packetErrors: ['Review the signed PDF.'], sent: false };
const findings = deterministicQa(input);
assert.ok(findings.some(f => f.id === 'date-conflict'));
assert.ok(findings.some(f => f.id === 'passenger-files'));
assert.ok(findings.some(f => f.id === 'packet-0'));
assert.ok(!findings.some(f => f.id.startsWith('first-contact-')));
const sources = qaSources(input), payload = JSON.stringify(sources);
assert.doesNotMatch(payload, /123456789|Private Passenger|1980-01-01|DO NOT SEND/);
assert.match(payload, /Rear-ended/);
assert.doesNotMatch(redactQaText('SSN 123-45-6789 and social security number: 987654321'), /123|987/);
assert.deepEqual(deterministicQa({ ...input, sent: true }).map(f => f.id), ['already-sent']);
const netfly = qaSources({ ...input, flow: 'netfly', answers: { fields: { incident_story: 'Rear-ended', dob: '1980-01-01', mailing_address: 'Secret Street', seen_doctor: 'No' } } });
assert.doesNotMatch(JSON.stringify(netfly), /1980|Secret Street/);
assert.equal(narrativeQa({ findings: [{ field: 'seen_doctor', message: 'Confirm whether care began.', quotes: [{ source: 'seen_doctor', text: 'No' }] }] }, netfly)?.length, 1);
assert.equal(narrativeQa({ findings: [{ field: 'notes', message: 'Invented concern', quotes: [{ source: 'notes', text: 'The client was speeding' }] }] }, sources), null);
assert.equal(narrativeQa({ findings: [{ field: 'wrong_field', message: 'Wrong', quotes: [{ source: 'notes', text: 'Rear-ended.' }] }] }, sources), null);
assert.equal(narrativeQa({ findings: [{ field: 'notes', message: '', quotes: [{ source: 'notes', text: 'Rear-ended.' }] }] }, sources), null);
assert.deepEqual(narrativeQa({ findings: [] }, sources), []);
console.log('File QA: canonical gaps, dates, passengers, sent protection, PII projection and quote validation passed');
