'use client';
import { useState } from 'react';
import { PAYROLL_GROUPS, addDays, payrollCsv, payrollTotals, processedLine, type PayrollGroup, type PayrollReport, type PayrollRow } from '@/lib/payroll';
import type { payrollView } from '@/lib/payroll-server';
import './payroll.css';
type View = ReturnType<typeof payrollView> & {token:string};
const short=(day:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'));
function combine(sections:View['sections']):PayrollReport {
  const reports=sections.map(s=>s.report), first=reports[0];
  return {...first,rows:reports.flatMap(r=>r.rows),carried:reports.flatMap(r=>r.carried),undated:reports.flatMap(r=>r.undated),unresolved:reports.flatMap(r=>r.unresolved),adjustments:reports.flatMap(r=>r.adjustments),rejectionReview:reports.flatMap(r=>r.rejectionReview)};
}
export default function Payroll({initial}:{initial:View}) {
  const [view,setView]=useState(initial),[end,setEnd]=useState(initial.end),[filter,setFilter]=useState<PayrollGroup|null>(null);
  const [campaign,setCampaign]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [edit,setEdit]=useState<PayrollRow|null>(null),[op,setOp]=useState('attorney_hold'),[reason,setReason]=useState(''),[day,setDay]=useState(''),[agent,setAgent]=useState('');
  const [closing,setClosing]=useState(false),[confirm,setConfirm]=useState(false),[exclude,setExclude]=useState(false);
  const [lineId,setLineId]=useState(''),[processed,setProcessed]=useState(true);
  const [historyEnd,setHistoryEnd]=useState(addDays(initial.end,-7)),[billed,setBilled]=useState(true),[paid,setPaid]=useState(true);
  const all=combine(view.sections),closed=view.sections.length>0&&view.sections.every(s=>!!s.closedAt);
  const matches=(r:{name:string;leadNo:string;campaignId?:string})=>(!campaign||r.campaignId===campaign)&&(!query||(r.name+' '+r.leadNo).toLowerCase().includes(query.toLowerCase().trim()));
  const report={...all,rows:all.rows.filter(matches),carried:all.carried.filter(matches),undated:all.undated.filter(matches),unresolved:all.unresolved.filter(matches),adjustments:all.adjustments.filter(matches),rejectionReview:all.rejectionReview.filter(matches)};
  const counts=payrollTotals(report),total=payrollTotals(all),rows=report.rows.filter(r=>!filter||r.group===filter);
  const campaigns=Array.from(new Map([...all.rows,...all.carried,...all.undated,...all.unresolved].map(r=>[r.campaignId,r.campaign])).entries());
  async function refresh(next=end) {
    setBusy(true);setError('');
    try { const r=await fetch('/api/payroll?end='+encodeURIComponent(next),{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setView(j);setEnd(j.end);setClosing(false);setConfirm(false);setExclude(false);return true; }
    catch(e){setError(e instanceof Error?e.message:'Could not load payroll.');return false;}finally{setBusy(false);}
  }
  async function save(body:any) {
    setBusy(true);setError('');setMessage('');
    try {const r=await fetch('/api/payroll',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error);
      setEdit(null);setLineId('');setReason('');const refreshed=await refresh(view.end);setMessage(refreshed?(body.op==='close'?'Period closed. The billing and payroll list is saved.':'Saved. Payroll totals have been refreshed.'):'The change saved, but the refreshed totals could not load. Refresh before continuing.');}
    catch(e){setError(e instanceof Error?e.message:'The change has not saved.');}finally{setBusy(false);}
  }
  function open(row:PayrollRow,action:string) {setEdit(row);setOp(action);setReason('');setDay(row.signedDay||'');setAgent(row.creditedAgentId||'');setError('');}
  function download(){const href=URL.createObjectURL(new Blob([payrollCsv(report)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=href;a.download='ClaimReach-payroll-'+view.end+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
  const list=(items:PayrollRow[],empty:string)=><div className="pr-table"><div className="pr-row pr-columns"><span>Client / file</span><span>Agent</span><span>Signed / status</span><span>Billing / commission</span><span>Action</span></div>
    {items.map(r=><div className="pr-row" key={r.claimId}><div><a href={r.href}>{r.name}</a><small>{r.leadNo} · {r.campaign}</small></div><div><b>{r.creditedAgent}</b></div>
      <div><b>{r.signedDay?short(r.signedDay):'Signing date needed'}</b><small>{PAYROLL_GROUPS[r.group]}</small>{r.group==='rejected'&&<small>{r.firmReason}</small>}{r.holdReason&&<small>{r.holdReason}</small>}</div>
      <div><b>{r.bill?(closed?'Billed':'Bill'):'—'} / {r.pay?(closed?'Paid':'Pay'):'—'}</b><small>{r.blocked}</small>{r.signedDay&&r.signedDay<view.start&&<small>Original week: {short(r.originalPeriod!)}</small>}</div>
      <div>{!closed&&<button disabled={busy} onClick={()=>open(r,!r.signedDay?'signature_date':r.group==='hold'?'attorney_release':!r.creditedAgentId?'agent_credit':'attorney_hold')}>Manage</button>}</div></div>)}{!items.length&&<p className="pr-empty">{empty}</p>}</div>;
  return <main className="payroll"><header className="pr-heading"><div><p className="pr-eyebrow">OWNER · ALL MVA CAMPAIGNS</p><h1>Payroll & billing</h1><p>One week. Every signed file. A separate record of later adjustments.</p></div><button disabled={busy} onClick={download}>Download payroll list</button></header>
    <section className="pr-period"><div><b>{short(view.start)} – {short(view.end)}</b><span>Signed Monday–Sunday · Pacific time</span><small>Wednesday cutoff: {short(view.cutoff)} · {closed?'Closed — saved history':'Open — review before closing'}</small></div>
      <div className="pr-period-controls"><button aria-label="Previous pay period" disabled={busy} onClick={()=>refresh(addDays(view.end,-7))}>←</button><label>Week ending<input type="date" value={end} disabled={busy} onChange={e=>setEnd(e.target.value)}/></label><button disabled={busy} onClick={()=>refresh(end)}>View week</button><button aria-label="Next pay period" disabled={busy} onClick={()=>refresh(addDays(view.end,7))}>→</button></div></section>
    {error&&<p className="pr-error" role="alert">{error}</p>}{message&&<p className="pr-success" role="status">{message}</p>}
    <div className="pr-filters"><label>Campaign<select value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">All MVA campaigns</option>{campaigns.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Find a client<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or lead number"/></label><button disabled={busy} onClick={()=>refresh(view.end)}>Refresh</button></div>
    <nav className="pr-counts" aria-label="Signed files in this pay period">{(Object.keys(PAYROLL_GROUPS) as PayrollGroup[]).map(k=><button key={k} aria-pressed={filter===k} onClick={()=>setFilter(filter===k?null:k)}><strong>{counts.groups[k]}</strong><span>{PAYROLL_GROUPS[k]}</span></button>)}</nav>
    <section className="pr-section"><header><div><h2>{filter?PAYROLL_GROUPS[filter]:'Signed this period'} <span>{rows.length}</span></h2><p>Each file appears in one group. Waiting on attorney means an explicit hold before billing or payroll.</p></div>{filter&&<button onClick={()=>setFilter(null)}>Show all five groups</button>}</header>{list(rows,'No signed files match this period and these filters.')}</section>
    {!!report.carried.length&&<section className="pr-section"><header><div><h2>Older files now ready <span>{report.carried.length}</span></h2><p>These keep their original signing week. Bill/pay them here once; they are outside the five counts above.</p></div></header>{list(report.carried,'No older files ready.')}</section>}
    <section className="pr-section"><header><div><h2>Prior-period credits & clawbacks</h2><p>Only previously billed or paid entries qualify. A rejection before the first payroll does not create a deduction.</p></div></header><div className="pr-table">
      {report.adjustments.map(a=><div className="pr-adjustment" key={a.sourceId}><div><a href={a.href}>{a.name}</a><small>{a.leadNo} · Originally processed week of {short(a.originalPeriod)}</small></div><div><b>{a.kind==='firm_credit'?'Credit firm':'Claw back commission'}</b><small>{a.kind==='clawback'?a.agent:''}</small></div><div>{a.reason}<small>Rejected {new Date(a.rejectedAt).toLocaleDateString('en-US',{timeZone:'America/Los_Angeles'})}</small></div></div>)}
      {!report.adjustments.length&&<p className="pr-empty">No recorded prior payments need an adjustment in this payroll.</p>}</div></section>
    {!!(report.undated.length||report.unresolved.length)&&<details className="pr-attention"><summary>Needs review · {report.undated.length} without a signing date · {report.unresolved.length} unverified</summary><p>These are excluded from the period counts. Record the actual signature date from the signed document; an import date is not a signing date.</p>{list(report.undated,'All confirmed signatures have a date.')}{list(report.unresolved,'No unverified agreements.')}</details>}
    {!!report.rejectionReview.length&&<details className="pr-attention"><summary>Older rejections · check previous billing / payment · {report.rejectionReview.length}</summary><p>No prior billing or payment is recorded for these files. They create no deduction unless you record the original invoice or commission here.</p>{list(report.rejectionReview,'No prior history needs review.')}</details>}
    {edit&&<section className="pr-editor" aria-label="Manage payroll file"><header><div><h2>{edit.name} · {edit.leadNo}</h2><p>Changes have an audit history. Previous closed payrolls stay intact.</p></div><button disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></header>
      <label>Action<select value={op} onChange={e=>setOp(e.target.value)}><option value="attorney_hold">Hold — waiting on attorney</option><option value="attorney_release">Attorney cleared — release hold</option>{!edit.signedAt&&<option value="signature_date">Confirm original signing date</option>}<option value="agent_credit">Choose credited agent</option><option value="history">Record previous billing / payment</option></select></label>
      {op==='signature_date'&&<label>Actual signing date<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label>}{(op==='agent_credit'||op==='history'&&paid)&&<label>Credited agent<select value={agent} onChange={e=>setAgent(e.target.value)}><option value="">Choose agent</option>{view.agents.map(a=><option key={a.id} value={a.id}>{a.full_name}</option>)}</select></label>}
      {op==='history'&&<div className="pr-confirm"><p>Use the prior invoice or payroll as evidence. This does not bill or pay again.</p><label>Original pay period ending Sunday<input type="date" value={historyEnd} onChange={e=>setHistoryEnd(e.target.value)}/></label><label><input type="checkbox" checked={billed} onChange={e=>setBilled(e.target.checked)}/> Firm was billed</label><label><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/> Agent commission was paid</label></div>}
      <label>Reason / source<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Attorney said…, signed PDF date…, or invoice / payroll reference"/></label><button className="pr-primary" disabled={busy||reason.trim().length<3} onClick={()=>save({op,claim:edit.claimId,reason,day,agent,end:historyEnd,billed,paid})}>Save change</button></section>}
    <section className="pr-close"><div><h2>{closed?'Saved payroll':'Ready for Wednesday'}</h2><p>{total.bill} {closed?'billed':'to bill'} · {total.pay} commissions {closed?'paid':'to pay'} · {total.credit} firm credits · {total.clawback} clawbacks</p><small>All MVA campaigns, regardless of filters. Net: {total.bill-total.credit} billing items / {total.pay-total.clawback} commission items. Dollar rates are not calculated here.</small></div>
      {!closed&&!closing&&<button className="pr-primary" disabled={busy} onClick={()=>setClosing(true)}>Review & close period</button>}
      {!closed&&closing&&<div className="pr-confirm"><p>Closing saves this list and records its billing, payments, credits and clawbacks as processed for monthly Wave reconciliation. It does not send invoices or transfer funds.</p><label><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> I reviewed the full list and will process these billing and payroll entries.</label>{!!(all.undated.length||all.unresolved.length)&&<label><input type="checkbox" checked={exclude} onChange={e=>setExclude(e.target.checked)}/> I reviewed the {all.undated.length} undated and {all.unresolved.length} unverified files excluded from this period.</label>}<div><button disabled={busy} onClick={()=>setClosing(false)}>Keep open</button><button className="pr-primary" disabled={busy||!confirm||!!(all.undated.length||all.unresolved.length)&&!exclude} onClick={()=>save({op:'close',end:view.end,token:view.token,confirmProcessed:confirm,confirmExcluded:exclude})}>{busy?'Saving…':'Close period & save payroll'}</button></div></div>}
    </section>
    <details className="pr-attention"><summary>Monthly Wave reconciliation · {view.lines.length} ledger entries</summary><p>Closing payroll treats the approved list as processed. Record any difference here with its Wave or payroll reference. Corrections stay in history.</p>
      <label>Ledger entry<select value={lineId} onChange={e=>{setLineId(e.target.value);setReason('');}}><option value="">Choose an entry</option>{view.lines.map(l=><option key={l.id} value={l.id}>{l.data.leadNo} · {l.data.name} · {l.kind} · {l.period_start} · {processedLine(l,view.notes)?'processed':'not processed'}</option>)}</select></label>
      {lineId&&<div className="pr-reconcile"><label>Actual result<select value={String(processed)} onChange={e=>setProcessed(e.target.value==='true')}><option value="true">Processed</option><option value="false">Not processed</option></select></label><label>Wave / payroll reference and reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<3} onClick={()=>save({op:'reconcile',claim:view.lines.find(l=>l.id===lineId)!.claim_id,line:lineId,processed,reason})}>Save reconciliation</button></div>}
    </details><p className="pr-footnote">The seven-day firm review window remains on the file. It does not delay Wednesday billing or payroll. <a href="/reports/inno">Open the original signature evidence report</a>.</p>
  </main>;
}
