// ============================================================================
// SEED GENERATOR
//
// Emits the migration that moves questions out of code and into intake_forms.
// Run: npx tsx scripts/gen-master-forms.ts > supabase/migrations/0070_master_forms.sql
//
// Nothing here authors content. Each master form is a mechanical conversion of a
// definition that already exists in the repo and has already been approved:
//
//   mva                 AUTO_QUESTIONS   (questions.ts, via to-form.ts)
//   prem                GPI_QUESTIONS    (questions.ts, via to-form.ts)
//   motel_trafficking   INTAKE           (questionnaire.ts, already Field[])
//   medmal              MEDMAL_INTAKE    (medmal.ts, already Field[])
//
// The mva and prem conversions are asserted lossless by parity.test.ts before
// this runs. motel and medmal are already Field[], so they are copied verbatim
// with locking metadata applied.
//
// referral is deliberately NOT seeded here. Merging CRIMINAL_QUESTIONS,
// FAMILY_QUESTIONS and BRIEF_QUESTIONS into one form collides on shared keys
// (what_happened, incident_date, state, represented) that carry DIFFERENT
// approved scripts per matter. Picking one would silently rewrite approved
// wording, so it needs a decision rather than a default.
// ============================================================================
import { AUTO_QUESTIONS, GPI_QUESTIONS } from "../src/lib/intake-console/questions";
import { generateForm } from "../src/lib/intake-console/to-form";
import { INTAKE, type Field } from "../src/lib/questionnaire";
import { MEDMAL_INTAKE } from "../src/lib/medmal";

// Field ids the disposition engine matches on. These may be reworded and
// reordered; they may never be deleted or re-keyed.
const ROUTING_KEYS = new Set([
  "authority", "poa", "role", "attorney", "injured", "injuries", "symptoms_ongoing",
  "treatment", "willing", "willing_more", "surgery", "hosp", "fault", "commercial",
  "settled", "bills", "date", "presence", "agent_read", "represented",
  "what_happened", "incident_date", "state",
]);

function lock(fields: Field[]): Field[] {
  return fields.map((f) => {
    const out: Field = { ...f, origin: f.origin ?? (f.kind === "script" ? "script" : "spine"), locked: true };
    if (f.gateType) out.mandatoryGate = true;
    if (ROUTING_KEYS.has(f.id)) out.routingKey = true;
    return out;
  });
}

function sqlStr(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

interface Seed { caseType: string; name: string; fields: Field[]; askOrder: string[]; source: string }

const MVA = generateForm("mva", AUTO_QUESTIONS);
const PREM = generateForm("prem", GPI_QUESTIONS);

// Brett kept one thing from the beta_motel draft: a warm-welcome heading ahead
// of the opening. It is the only field that form had which the canonical
// questionnaire did not, so it is carried over rather than lost with the draft.
const MOTEL: Field[] = [
  { id: "s_warm_welcome", scope: "lead", kind: "section", label: "Warm welcome" },
  ...INTAKE,
];

const SEEDS: Seed[] = [
  { caseType: "mva", name: "MVA intake", fields: lock(MVA.fields), askOrder: MVA.askOrder,
    source: "questions.ts AUTO_QUESTIONS, converted by to-form.ts, parity asserted" },
  { caseType: "prem", name: "Premises intake", fields: lock(PREM.fields), askOrder: PREM.askOrder,
    source: "questions.ts GPI_QUESTIONS, converted by to-form.ts, parity asserted" },
  { caseType: "motel_trafficking", name: "Motel trafficking intake", fields: lock(MOTEL),
    askOrder: MOTEL.map((f) => f.id),
    source: "questionnaire.ts INTAKE plus the warm welcome section from the beta draft" },
  { caseType: "medmal", name: "Medical malpractice intake", fields: lock(MEDMAL_INTAKE),
    askOrder: MEDMAL_INTAKE.map((f) => f.id),
    source: "medmal.ts MEDMAL_INTAKE, copied verbatim" },
];

const out: string[] = [];
out.push(`-- ============================================================================
-- 0070 MASTER FORMS: QUESTIONS BECOME DATA
--
-- Generated by scripts/gen-master-forms.ts. Do not hand edit; regenerate.
--
-- A master form is firm_id null AND campaign_id null: the canonical questions
-- for a case type. Assigning a case type to a campaign links the master by
-- reference. The first edit forks a campaign-owned copy, so editing a master can
-- never rewrite questions on a live campaign and editing one campaign can never
-- affect another.
--
-- Field locking metadata is applied here:
--   origin/locked  spine content, not user-authored
--   mandatoryGate  the always-on gates
--   routingKey     ids the disposition engine matches on
-- A locked or routing-key field may be reworded and reordered. It may NEVER be
-- deleted or re-keyed: renaming \`injured\` makes the engine stop matching and
-- qualified files DQ with nothing surfacing the break.
--
-- Idempotent.
-- ============================================================================
`);

for (const s of SEEDS) {
  out.push(`
-- ---------------------------------------------------------------- ${s.caseType}
-- Source: ${s.source}
delete from intake_forms where claim_type = ${sqlStr(s.caseType)} and firm_id is null and campaign_id is null;
insert into intake_forms (firm_id, campaign_id, claim_type, name, description, status, version, fields, ask_order)
values (null, null, ${sqlStr(s.caseType)}, ${sqlStr(s.name)},
  ${sqlStr("Master form. " + s.source)},
  'published', 10,
  ${sqlStr(JSON.stringify(s.fields))}::jsonb,
  ${sqlStr(JSON.stringify(s.askOrder))}::jsonb);
`);
}

out.push(`
-- Verify: four master forms, each with a non-empty field list and ask order.
select claim_type, name, version,
       jsonb_array_length(fields) as field_count,
       jsonb_array_length(ask_order) as ask_count
from intake_forms
where firm_id is null and campaign_id is null
order by claim_type;
`);

console.log(out.join(""));
